optimizer:
  type: AdamW
  part: gft
  kwargs:
    lr: 0.0005
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: cfgs/dataset_configs/ScanObjectNN_objectbg.yaml
    others:
      subset: train
  val:
    _base_: cfgs/dataset_configs/ScanObjectNN_objectbg.yaml
    others:
      subset: test
  test:
    _base_: cfgs/dataset_configs/ScanObjectNN_objectbg.yaml
    others:
      subset: test

model:
  NAME: PointTransformer_GFT
  trans_dim: 384
  depth: 12
  drop_path_rate: 0.1
  drop_rate: 0.0
  cls_dim: 15
  num_heads: 6
  group_size: 32
  num_group: 128
  encoder_dims: 384 # or 256 for Point-BERT

  # EdgeConv configs
  k: 20
  in_dim: 384
  feat_dims: [64, 64, 64, 64]
  emb_dim: 256

  # Cross Attention configs
  cross_idx: [0, 3, 6, 9]
  cross_attn_heads: 2
  cross_attn_dim: 32
  alpha: 1.0
  cross_attn_drop_rate: 0.0

  # Prompt configs
  prompt_len: 50

npoints: 2048
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10.0